---

- import_tasks: install.yml
  tags: [mariadb]
  
- import_tasks: configure.yml
  tags: [mariadb]

- import_tasks: databases.yml
  tags: [mariadb]

- import_tasks: users.yml
  tags: [mariadb]

- import_tasks: "{{ mariadb_after_tasks_file | default('empty.yml') }}"

- import_tasks: supervisor-reg.yml
  when: mariadb_use_supervisor
  tags: [mariadb]
  
